pipeline {
    agent any
    environment {
        MAVEN_HOME = '/opt/maven'
        PATH = "${env.PATH}:${env.MAVEN_HOME}/bin"
    }
    stages {
        stage('Build') {
            steps {
                sh 'echo $PATH' // Confirm PATH includes Maven
                sh 'mvn -v'      // Verify that mvn command is accessible
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage('Complete') {
            steps {
                echo "complete"
            }
        }
    }
}
